### ISSUE TITLE
Calling from Browser to Element X App - Legacy Call Unsupported

### ISSUE THREAD

**Issue by ckaap** [element-hq/element-x-android#3937]
### Steps to reproduce

![photo_2024-11-25_10-59-34](https://github.com/user-attachments/assets/824aca54-9b0b-4386-804d-509899e6f02b)
Set up a Synapse Matrix server with Coturn configured for voice calls.
Use a web browser to initiate a voice call to a user on the mobile app Element X.
Observe the behavior when the call is received on Element X.

### Outcome

Expected Behavior: The call should successfully connect between the web browser and the Element X mobile app.
Actual Behavior: The call fails with the error message "Call not supported" on Element X.
Additional Information:

Voice calls from the web browser to the standard Element app or between web browsers work without issues.
Testing indicates that the problem is related to Legacy Call support, which appears to be unsupported in Element X.

root@element-synapse:~# cat /etc/turnserver.conf
```
listening-port=3478
tls-listening-port=5349
fingerprint
use-auth-secret
static-auth-secret=*turn_shared_secret*
realm=matrix.domain.com
user-quota=100
total-quota=1200
no-tcp-relay
syslog
no-multicast-peers
verbose
cert=/etc/letsencrypt/live/domain.com/fullchain.pem
pkey=/etc/letsencrypt/live/domain.com/privkey.pem
```
root@element-synapse:~# cat /etc/matrix-synapse/homeserver.yaml
```
pid_file: "/var/run/matrix-synapse.pid"
server_name: "matrix.domain.com"
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: matrix
    password: password
    database: matrix
    host: localhost
    port: 5432
    cp_min: 5
    cp_max: 10
log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: /var/lib/matrix-synapse/media
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
trusted_key_servers:
  - server_name: "matrix.domain.com"
suppress_key_server_warning: true
max_upload_size: 100M
enable_registration: false
matrix_synapse_federation_enabled: false
matrix_synapse_federation_port_enabled: false
registration_shared_secret: "registration_shared_secret"
user_directory:
    enabled: true
    search_all_users: true
encryption_enabled_by_default_for_room_type: all
prefer_local_users: true
turn_uris:
  - "turn:matrix.domain.com:3478?transport=udp"
  - "turn:matrix.domain.com:3478?transport=tcp"
  - "turns:matrix.domain.com:5349?transport=tcp"
turn_shared_secret: "turn_shared_secret"
turn_user_lifetime: 86400000
turn_allow_guests: true
serve_server_wellknown: true
admin_users:
  - "@admin:matrix.domain.com"
```

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes
